### ISSUE TITLE
Rack adapter missing

### ISSUE THREAD

**Issue by notEthan** [lostisland/awesome-faraday#7]
the [rack adapter](https://github.com/lostisland/faraday-rack) is not listed. I'd PR a fix but I'm not sure about a number of entries in the adapter table.

**Comment by olleolleolle** [comment]
@notEthan Please open a PR and have open questions in it, the questions can probably be answered by others. Thanks in advance!

**Comment by notEthan** [comment]
opened https://github.com/lostisland/awesome-faraday/pull/8; closing
